### ISSUE TITLE
코드 개선 방안#1

### ISSUE THREAD

**Issue by geusan** [prography/6th-snowflake-react-native#71]
https://github.com/prography/6th-snowflake-react-native/blob/e950611db29eaa5bce17a194025266bf5d85edb7/src/utils/functions.ts

```javascript
export const llog = (...params: any[]) => {
    if (__DEV__) {
        console.log(...params);
    }
}
```

이렇게하면 llog 1, 2, 3, 4 로 나눌 필요 없을 것 같아보여서 이슈하나 올려봅니다.

**Comment by daheeahn** [comment]
감사합니다 👍  @geusan

**Comment by daheeahn** [comment]
하나 배워갑니다!!

**Comment by geusan** [comment]
> 감사합니다 👍 @geusan

화이팅입니다!😁
